name: CD Pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI Pipeline]
    types: [completed]
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing
        run: echo "CD test complete"
