name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Testing
      run: echo "CI test complete"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./ # Example of what to upload, adjust this path to your actual build files
