name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - uses: actions/checkout@v4
    - name: Build the Docker image 
      working-directory: testingweb
      run: |
        docker build . -t 381491834376.dkr.ecr.us-east-1.amazonaws.com/myappcontainer:latest
        docker push 381491834376.dkr.ecr.us-east-1.amazonaws.com/myappcontainer:latest
        